language: node_js
node_js:
  - 'stable'
notifications:
  email: false
cache: yarn

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  on:
    branch: master

